FORMAT: 1A
HOTS: 127.0.0.1

# Hogan Practice

## Hogan Practice API Blueprint
- Header
```json
{
    "access-token": "{your-access-token}",
    "Content-Type": "application/json"
}
```

# Test Playlists
<!-- include(/playlists/test/test-playlists.md) -->

# Test Playlists Track
<!-- include(/playlists/test/test-playlists-track.md) -->